services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql:14.1.0-debian-10-r31
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: woa
    volumes:
      - postgres_data:/bitnami/postgresql
    ports:
      - 5432:5432
volumes:
  postgres_data:
